name: Telegram Notification

# Ref: 
# 1. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# 2. https://github.com/marketplace/actions/telegram-message-notify

on:
  workflow_run:
    workflows: 
      - Theme Release
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ---
            Action: https://github.com/${{ github.repository }}/actions 
            Release: https://github.com/${{ github.repository }}/releases 
            Result: ✅ success
            Workflow: ${{ github.event.workflow_run.name }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            ---

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ---
            Action: https://github.com/${{ github.repository }}/actions 
            Result: ❌ failure
            Workflow: ${{ github.event.workflow_run.name }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            ---
